management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  #服务端口号
  port: 8080

spring:
  profiles:
    active: dev
  data:
    #MongoDB configuration
    mongodb:
      host: mongo
      port: 27017
      database: oomall_demo
#  mongodb:
#    database: oomall
#    username: demouser
#    password: '123456'
#    authentication-database: oomall
#    replica-set: rs0
#    read-preference: nearest
#    hosts: mongo1:27017,mongo1:27018,mongo1:27019
  jackson:
    #JSON的时间数据的时区
    time-zone: GMT+8

logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG

